services:
  - type: web
    name: sshweather-app
    env: docker
    repo: https://github.com/Jazjmjk/sshweatherapp
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_TOOL_OPTIONS
        value: -Duser.timezone=America/Mexico_City
